#!/bin/sh

url=$1
echo ">> Creating downloads directory"
mkdir downloads

echo ">> Downloading artifact: $url"
wget -nd -q $url -P downloads/

function tarToZip() {
  artifactWithPrefix=${f%.tar.*}
  artifactWithoutPrefix=${artifactWithPrefix#downloads/}

  mkdir $artifactWithPrefix
  echo ">> Untarring $f"
  tar -C downloads -xf $f
  cd downloads
  echo ">> Zipping $f to zips/${artifactWithoutPrefix}.zip"
  zip -qr "../zips/${artifactWithoutPrefix}.zip" $artifactWithoutPrefix
  echo ">> Removing $artifactWithPrefix"
  rm -rf ../$artifactWithPrefix
}

for f in downloads/*.tar.*; do \
  tarToZip
done

echo ">> Destroying downloads directory"
rm -rf downloads/
